# Generated by Django 4.1.7 on 2023-03-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TboProject', '0002_alter_objectlocations_finvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectlocations',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='objectlocations',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
